version: '3'

services:
  app:
    build: .
    volumes:
      - .:/gantt-chart-app
    command: yarn dev
    ports:
      - 8000:3000
    container_name: gantt-chart-app

  storybook:
    build: .
    volumes:
      - .:/gantt-chart-app
    command: yarn storybook
    ports:
      - 6006:6006
    container_name: gantt-chart-app-storybook
